// civ_logic.js
const CIV_SYLLABUS = [
    { "topic": "I. EFFECT AND APPLICATION OF LAWS", "depth": 1 },
    { "topic": "A. When Laws Take Effect – NCC, Art. 2", "depth": 2 },
    { "topic": "B. Ignorance of the Law – NCC, Art. 3", "depth": 2 },
    { "topic": "C. Retroactivity of Laws – NCC, Art. 4", "depth": 2 },
    { "topic": "D. Mandatory and Prohibitory Laws – NCC, Art. 5", "depth": 2 },
    { "topic": "E. Waiver – NCC, Art. 6", "depth": 2 },
    { "topic": "F. Repeal and Nullification of Laws – NCC, Art. 7", "depth": 2 },
    { "topic": "G. Judicial Decisions – NCC, Art. 8", "depth": 2 },
    { "topic": "H. Legal Periods – NCC, Art. 13; Revised Administrative Code of 1987, Book I, Chapter VIII, Sec. 31", "depth": 2 },
    { "topic": "I. Territoriality of Penal Laws – NCC, Art. 14", "depth": 2 },
    { "topic": "J. Conflict of Laws – NCC, Arts. 15-18", "depth": 2 },

    { "topic": "II. PERSONS", "depth": 1 },
    { "topic": "A. Juridical capacity", "depth": 2 },
    { "topic": "B. Capacity to Act", "depth": 2 },

    { "topic": "III. FAMILY CODE", "depth": 1 },
    { "topic": "Family Code of the Philippines (FC) – Executive Order No. 209, as amended", "depth": 2 },
    { "topic": "A. Marriage – FC, Articles 1-148; 1987 Constitution, Art. II, Sec. 12 and Art. XV", "depth": 2 },
    { "topic": "B. Family Relations", "depth": 2 },

    { "topic": "IV. CIVIL REGISTER", "depth": 1 },
    { "topic": "A. Required Entries – NCC, Arts. 407-408", "depth": 2 },
    { "topic": "B. Correction of Entries", "depth": 2 },

    { "topic": "V. PROPERTY, OWNERSHIP, AND ITS MODIFICATIONS", "depth": 1 },
    { "topic": "A. Property", "depth": 2 },
    { "topic": "B. Ownership", "depth": 2 },
    { "topic": "C. Modes of Acquiring Ownership", "depth": 2 },

    { "topic": "VI. LAND TITLES AND DEEDS", "depth": 1 },
    { "topic": "P.D. No. 1529, as amended", "depth": 2 },
    { "topic": "A. Torrens System", "depth": 2 },
    { "topic": "B. Regalian Doctrine", "depth": 2 },
    { "topic": "C. Nationality Restrictions on Land Ownership", "depth": 2 },
    { "topic": "D. Original Registration", "depth": 2 },
    { "topic": "E. Confirmation of Imperfect Title – R.A. No. 11573", "depth": 2 },
    { "topic": "F. Certificate of Title", "depth": 2 },
    { "topic": "G. Subsequent Registration", "depth": 2 },
    { "topic": "H. Non-registrable Properties", "depth": 2 },
    { "topic": "I. Dealings with Unregistered Lands", "depth": 2 },
    { "topic": "J. Assurance Fund", "depth": 2 },
    { "topic": "K. Reconstitution of Title – R.A. No. 26", depth: 2 },

    { "topic": "VII. SUCCESSION", "depth": 1 },
    { "topic": "A. Definition – NCC, Arts. 774 and 712", "depth": 2 },
    { "topic": "B. Elements", "depth": 2 },
    { "topic": "C. Testamentary Succession – NCC, Arts. 783-959", "depth": 2 },
    { "topic": "D. Intestate Succession – NCC, Arts. 960-1014", "depth": 2 },
    { "topic": "E. Common Provisions – NCC, Arts. 1015-1105", "depth": 2 },
    { "topic": "F. Distribution of Estate", "depth": 2 },

    { "topic": "VIII. OBLIGATIONS AND CONTRACTS", "depth": 1 },
    { "topic": "A. Obligations", "depth": 2 },
    { "topic": "B. Contracts", "depth": 2 },

    { "topic": "IX. SPECIAL CONTRACTS", "depth": 1 },
    { "topic": "A. Sale", "depth": 2 },
    { "topic": "B. Lease", "depth": 2 },
    { "topic": "C. Agency", "depth": 2 },
    { "topic": "D. Credit Transactions", "depth": 2 },

    { "topic": "X. QUASI-CONTRACTS", "depth": 1 },
    { "topic": "A. Definition", "depth": 2 },
    { "topic": "B. Kinds", "depth": 2 },
    { "topic": "C. Other Quasi-contracts", "depth": 2 },

    { "topic": "XI. TORTS AND QUASI-DELICTS", "depth": 1 },
    { "topic": "A. Principles", "depth": 2 },
    { "topic": "B. The Tortfeasor", "depth": 2 },
    { "topic": "C. Proximate Cause", "depth": 2 },
    { "topic": "D. Classification of Torts", "depth": 2 },
    { "topic": "E. Defenses", "depth": 2 },
    { "topic": "F. Nuisance", "depth": 2 },
    { "topic": "G. Medical Negligence and Malpractice", "depth": 2 },

    { "topic": "XII. DAMAGES", "depth": 1 },
    { "topic": "A. General Considerations", "depth": 2 },
    { "topic": "B. Kinds", "depth": 2 },
    { "topic": "C. Damages in Case of Death", "depth": 2 },
    { "topic": "D. Duty of Injured Party", "depth": 2 }
];
